//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaWeb.UsuariosServ {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuarios", Namespace="http://schemas.datacontract.org/2004/07/CapaDato")]
    [System.SerializableAttribute()]
    public partial class Usuarios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pass {
            get {
                return this.PassField;
            }
            set {
                if ((object.ReferenceEquals(this.PassField, value) != true)) {
                    this.PassField = value;
                    this.RaisePropertyChanged("Pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsuariosServ.IServicioUsuarios")]
    public interface IServicioUsuarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuarios/VerificarUsuarios", ReplyAction="http://tempuri.org/IServicioUsuarios/VerificarUsuariosResponse")]
        bool VerificarUsuarios(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuarios/VerificarUsuarios", ReplyAction="http://tempuri.org/IServicioUsuarios/VerificarUsuariosResponse")]
        System.Threading.Tasks.Task<bool> VerificarUsuariosAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuarios/BuscarUsuario", ReplyAction="http://tempuri.org/IServicioUsuarios/BuscarUsuarioResponse")]
        CapaWeb.UsuariosServ.Usuarios BuscarUsuario(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuarios/BuscarUsuario", ReplyAction="http://tempuri.org/IServicioUsuarios/BuscarUsuarioResponse")]
        System.Threading.Tasks.Task<CapaWeb.UsuariosServ.Usuarios> BuscarUsuarioAsync(string usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioUsuariosChannel : CapaWeb.UsuariosServ.IServicioUsuarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioUsuariosClient : System.ServiceModel.ClientBase<CapaWeb.UsuariosServ.IServicioUsuarios>, CapaWeb.UsuariosServ.IServicioUsuarios {
        
        public ServicioUsuariosClient() {
        }
        
        public ServicioUsuariosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioUsuariosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool VerificarUsuarios(string usuario) {
            return base.Channel.VerificarUsuarios(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> VerificarUsuariosAsync(string usuario) {
            return base.Channel.VerificarUsuariosAsync(usuario);
        }
        
        public CapaWeb.UsuariosServ.Usuarios BuscarUsuario(string usuario) {
            return base.Channel.BuscarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<CapaWeb.UsuariosServ.Usuarios> BuscarUsuarioAsync(string usuario) {
            return base.Channel.BuscarUsuarioAsync(usuario);
        }
    }
}
