//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaWeb.ObraCompletoServ {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObraCompleto", Namespace="http://schemas.datacontract.org/2004/07/CapaEntidad")]
    [System.SerializableAttribute()]
    public partial class ObraCompleto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArtistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuidadosEspecialesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DimensionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstiloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcedenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Artista {
            get {
                return this.ArtistaField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistaField, value) != true)) {
                    this.ArtistaField = value;
                    this.RaisePropertyChanged("Artista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuidadosEspeciales {
            get {
                return this.CuidadosEspecialesField;
            }
            set {
                if ((object.ReferenceEquals(this.CuidadosEspecialesField, value) != true)) {
                    this.CuidadosEspecialesField = value;
                    this.RaisePropertyChanged("CuidadosEspeciales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dimensiones {
            get {
                return this.DimensionesField;
            }
            set {
                if ((object.ReferenceEquals(this.DimensionesField, value) != true)) {
                    this.DimensionesField = value;
                    this.RaisePropertyChanged("Dimensiones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estilo {
            get {
                return this.EstiloField;
            }
            set {
                if ((object.ReferenceEquals(this.EstiloField, value) != true)) {
                    this.EstiloField = value;
                    this.RaisePropertyChanged("Estilo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaIngreso {
            get {
                return this.FechaIngresoField;
            }
            set {
                if ((this.FechaIngresoField.Equals(value) != true)) {
                    this.FechaIngresoField = value;
                    this.RaisePropertyChanged("FechaIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Procedencia {
            get {
                return this.ProcedenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcedenciaField, value) != true)) {
                    this.ProcedenciaField = value;
                    this.RaisePropertyChanged("Procedencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Salon {
            get {
                return this.SalonField;
            }
            set {
                if ((object.ReferenceEquals(this.SalonField, value) != true)) {
                    this.SalonField = value;
                    this.RaisePropertyChanged("Salon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ObraCompletoServ.IServicioObraCompleto")]
    public interface IServicioObraCompleto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioObraCompleto/ListarObrasCompleto", ReplyAction="http://tempuri.org/IServicioObraCompleto/ListarObrasCompletoResponse")]
        CapaWeb.ObraCompletoServ.ObraCompleto[] ListarObrasCompleto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioObraCompleto/ListarObrasCompleto", ReplyAction="http://tempuri.org/IServicioObraCompleto/ListarObrasCompletoResponse")]
        System.Threading.Tasks.Task<CapaWeb.ObraCompletoServ.ObraCompleto[]> ListarObrasCompletoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioObraCompleto/ListarObrasCompleto365", ReplyAction="http://tempuri.org/IServicioObraCompleto/ListarObrasCompleto365Response")]
        CapaWeb.ObraCompletoServ.ObraCompleto[] ListarObrasCompleto365();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioObraCompleto/ListarObrasCompleto365", ReplyAction="http://tempuri.org/IServicioObraCompleto/ListarObrasCompleto365Response")]
        System.Threading.Tasks.Task<CapaWeb.ObraCompletoServ.ObraCompleto[]> ListarObrasCompleto365Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioObraCompleto/ListarObrasCompletoArtista", ReplyAction="http://tempuri.org/IServicioObraCompleto/ListarObrasCompletoArtistaResponse")]
        CapaWeb.ObraCompletoServ.ObraCompleto[] ListarObrasCompletoArtista(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioObraCompleto/ListarObrasCompletoArtista", ReplyAction="http://tempuri.org/IServicioObraCompleto/ListarObrasCompletoArtistaResponse")]
        System.Threading.Tasks.Task<CapaWeb.ObraCompletoServ.ObraCompleto[]> ListarObrasCompletoArtistaAsync(string rut);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioObraCompletoChannel : CapaWeb.ObraCompletoServ.IServicioObraCompleto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioObraCompletoClient : System.ServiceModel.ClientBase<CapaWeb.ObraCompletoServ.IServicioObraCompleto>, CapaWeb.ObraCompletoServ.IServicioObraCompleto {
        
        public ServicioObraCompletoClient() {
        }
        
        public ServicioObraCompletoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioObraCompletoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioObraCompletoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioObraCompletoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CapaWeb.ObraCompletoServ.ObraCompleto[] ListarObrasCompleto() {
            return base.Channel.ListarObrasCompleto();
        }
        
        public System.Threading.Tasks.Task<CapaWeb.ObraCompletoServ.ObraCompleto[]> ListarObrasCompletoAsync() {
            return base.Channel.ListarObrasCompletoAsync();
        }
        
        public CapaWeb.ObraCompletoServ.ObraCompleto[] ListarObrasCompleto365() {
            return base.Channel.ListarObrasCompleto365();
        }
        
        public System.Threading.Tasks.Task<CapaWeb.ObraCompletoServ.ObraCompleto[]> ListarObrasCompleto365Async() {
            return base.Channel.ListarObrasCompleto365Async();
        }
        
        public CapaWeb.ObraCompletoServ.ObraCompleto[] ListarObrasCompletoArtista(string rut) {
            return base.Channel.ListarObrasCompletoArtista(rut);
        }
        
        public System.Threading.Tasks.Task<CapaWeb.ObraCompletoServ.ObraCompleto[]> ListarObrasCompletoArtistaAsync(string rut) {
            return base.Channel.ListarObrasCompletoArtistaAsync(rut);
        }
    }
}
