//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MuseoEntities : DbContext
    {
        public MuseoEntities()
            : base("name=MuseoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Obra> Obra { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Tipo> Tipo { get; set; }
        public virtual DbSet<Ubicacion> Ubicacion { get; set; }
    }
}
