//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaWeb.ArtistaServ {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Artista", Namespace="http://schemas.datacontract.org/2004/07/CapaEntidad")]
    [System.SerializableAttribute()]
    public partial class Artista : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCompleto {
            get {
                return this.NombreCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompletoField, value) != true)) {
                    this.NombreCompletoField = value;
                    this.RaisePropertyChanged("NombreCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rut {
            get {
                return this.RutField;
            }
            set {
                if ((object.ReferenceEquals(this.RutField, value) != true)) {
                    this.RutField = value;
                    this.RaisePropertyChanged("Rut");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ArtistaServ.IServicioArtista")]
    public interface IServicioArtista {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioArtista/ListarArtistas", ReplyAction="http://tempuri.org/IServicioArtista/ListarArtistasResponse")]
        CapaWeb.ArtistaServ.Artista[] ListarArtistas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioArtista/ListarArtistas", ReplyAction="http://tempuri.org/IServicioArtista/ListarArtistasResponse")]
        System.Threading.Tasks.Task<CapaWeb.ArtistaServ.Artista[]> ListarArtistasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioArtistaChannel : CapaWeb.ArtistaServ.IServicioArtista, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioArtistaClient : System.ServiceModel.ClientBase<CapaWeb.ArtistaServ.IServicioArtista>, CapaWeb.ArtistaServ.IServicioArtista {
        
        public ServicioArtistaClient() {
        }
        
        public ServicioArtistaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioArtistaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioArtistaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioArtistaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CapaWeb.ArtistaServ.Artista[] ListarArtistas() {
            return base.Channel.ListarArtistas();
        }
        
        public System.Threading.Tasks.Task<CapaWeb.ArtistaServ.Artista[]> ListarArtistasAsync() {
            return base.Channel.ListarArtistasAsync();
        }
    }
}
